// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddUserWorkoutInput struct {
	UserEmail string               `json:"userEmail"`
	GymDay    string               `json:"gymDay"`
	Exercises []*EachExerciseInput `json:"exercises"`
}

type AvoidGiven struct {
	Name *string `json:"name"`
}

type BaseExercise struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	MuscleGroup   string  `json:"muscleGroup"`
	SpecificParts string  `json:"specificParts"`
	Level         int     `json:"level"`
	AvoidGiven    *string `json:"avoidGiven"`
	MovementType  string  `json:"movementType"`
}

type Body struct {
	Name string `json:"name"`
}

type CreateUserInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
}

type EachExercise struct {
	ID              string `json:"id"`
	WorkoutPerDayID string `json:"workoutPerDayId"`
	Name            string `json:"name"`
	Weight          int    `json:"weight"`
	Unit            string `json:"Unit"`
	Sets            int    `json:"Sets"`
	Reps            int    `json:"Reps"`
}

type EachExerciseInput struct {
	Name   string `json:"name"`
	Weight int    `json:"weight"`
	Unit   string `json:"Unit"`
	Sets   int    `json:"Sets"`
	Reps   int    `json:"Reps"`
}

type MuscleGroup struct {
	Name string `json:"name"`
}

type MuscleGroupSpecific struct {
	ID            string `json:"id"`
	MuscleGroup   string `json:"muscleGroup"`
	SpecificParts string `json:"specificParts"`
}

type User struct {
	ID             string  `json:"id"`
	WorkoutCycleID *string `json:"workoutCycleId"`
	FirstName      string  `json:"firstName"`
	LastName       string  `json:"lastName"`
	Email          string  `json:"email"`
	Password       string  `json:"password"`
}

type UserWorkoutPlan struct {
	WorkoutCycleID  string `json:"workoutCycleId"`
	WorkoutPerDayID string `json:"workoutPerDayId"`
	WorkoutDay      string `json:"workoutDay"`
	ExerciseName    string `json:"exerciseName"`
	Weight          int    `json:"weight"`
	Unit            string `json:"unit"`
	Sets            int    `json:"sets"`
	Reps            int    `json:"reps"`
}

type WorkoutCycle struct {
	ID     string `json:"id"`
	UserID string `json:"userId"`
	Name   string `json:"name"`
}

type WorkoutPerDay struct {
	ID             string  `json:"id"`
	WorkoutCycleID string  `json:"workoutCycleId"`
	GymDay         string  `json:"gymDay"`
	ExerciseID     *string `json:"exerciseId"`
}

type BaseExerciseInput struct {
	Name          string  `json:"name"`
	MuscleGroup   string  `json:"muscleGroup"`
	SpecificParts string  `json:"specificParts"`
	Level         int     `json:"level"`
	AvoidGiven    *string `json:"avoidGiven"`
	MovementType  string  `json:"movementType"`
}

type MuscleSpecificInput struct {
	Name string `json:"name"`
}
